services:
  - type: web
    name: ccchk-ub
    runtime: python
    repo: https://github.com/happyidgc-blip/ccchk-ub
    branch: main
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m ubb

    envVars:
      - key: API_ID
        value: 33798531
      - key: API_HASH
        value: "5daa87783e064820a001056e97891e6e"
      - key: STRING_SESSION
        value: "AQIDuYMAMuMhiYLeKGUsczQ7Db8IhN36OLR9ihO_ummN9Jc1Iz4HK4PY9WABt2Trc4H7p9DehTghyhsNr9rsBk-NWN2C2PV_PoFhSt_Dir6qcZM8eI074E6CjArNK2AYilaFTEELGHloojaduimv5YTCiWM4lZjhMDsoonOnnBHgFrJ-H_lh5LJhf_QADwb20ManewsYquvFD9AYZFkaX3XmCJrqLMSDcEMDKPNxfyzK0owkTBTn1CSly_X-l_5UJHZjBWNuJ1h8drDIUbdASFrSXH_bdUI4gr6tMUltlC2I8fn_bfylheQIudIprJawJJ4-ABx-B76bevkQSilWfMTX_Rm0PgAAAAHwxqJsAA"
      - key: DUMP_ID
        value: -1003820179176
