services:
  - type: web
    name: ccchk-ub
    runtime: python
    repo: https://github.com/happyidgc-blip/ccchk-ub
    branch: main
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m ubb

    envVars:
      - key: API_ID
        value: 123456
      - key: API_HASH
        value: "your_api_hash_here"
      - key: STRING_SESSION
        value: "your_telethon_session_string_here"
      - key: DUMP_ID
        value: -1001234567890
